CREATE TABLE PERSON(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30),
    SURNAME VARCHAR(30)
    );

CREATE TABLE POSTS(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(30),
    CONTENT VARCHAR(255),
    PERSON_ID INT , 
    FOREIGN KEY POST(PERSON_ID) REFERENCES PERSON(ID)
    );